[package]
name = "multi-party-ed25519"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
curv = { git = "https://github.com/KZen-networks/curv-replica" , tag = "v0.2.0", features =  ["ec_ed25519"]}
hex = "0.3.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
